# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a5cc937aa85858ddc9fb82d6966055eed01137f78a43668074170b765945a59d4566dd0839a175d6d69eccc779fbb1c3780b508c9c26ad2e9a5ebc912174426

test:
  secret_key_base: 6c6e99fd3afb43b1372ba2cf40cbecfd0e2fc01f7cffdbeec117c243d3f7e0db6932b1c5df3a467438ecbcd3a299446c026c369649ff643396fe14ff4826759d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
